import logging
import subprocess
import datetime
import asyncio
import os
import time
import shutil
import requests
import aiohttp
import aiofiles

from pathlib import Path
from p_bar import progress_bar
from pyrogram.types import Message
from pyrogram import Client


USER_AGENT = (
    "Mozilla/5.0 (X11; Linux x86_64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/120.0 Safari/537.36"
)


def duration(filename):
    try:
        result = subprocess.run(
            [
                "ffprobe",
                "-v", "error",
                "-show_entries", "format=duration",
                "-of", "default=noprint_wrappers=1:nokey=1",
                filename,
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        if result.returncode != 0:
            return 0
        return int(float(result.stdout.strip()))
    except Exception as e:
        logging.error(f"Duration error: {e}")
        return 0


async def download(url, name):
    """
    Download PDF/file from URL.
    """
    filename = f"{name}.pdf"

    timeout = aiohttp.ClientTimeout(total=None, sock_connect=60, sock_read=120)

    async with aiohttp.ClientSession(timeout=timeout) as session:
        async with session.get(url, headers={"User-Agent": USER_AGENT}) as resp:
            if resp.status != 200:
                raise Exception(f"Download failed: HTTP {resp.status}")

            async with aiofiles.open(filename, mode="wb") as f:
                async for chunk in resp.content.iter_chunked(1024 * 1024):
                    if chunk:
                        await f.write(chunk)

    return filename


async def run(cmd):
    """
    Run Linux shell command async.
    """
    proc = await asyncio.create_subprocess_shell(
        cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )

    stdout, stderr = await proc.communicate()

    out = stdout.decode(errors="ignore") if stdout else ""
    err = stderr.decode(errors="ignore") if stderr else ""

    logging.info(f"CMD exited {proc.returncode}: {cmd}")

    if out:
        logging.info(out)
    if err:
        logging.error(err)

    if proc.returncode != 0:
        return False

    return out or err or True


def old_download(url, file_name, chunk_size=1024 * 1024):
    """
    Simple sync download fallback.
    """
    if os.path.exists(file_name):
        os.remove(file_name)

    with requests.get(
        url,
        allow_redirects=True,
        stream=True,
        headers={"User-Agent": USER_AGENT},
        timeout=60,
    ) as r:
        r.raise_for_status()
        with open(file_name, "wb") as fd:
            for chunk in r.iter_content(chunk_size=chunk_size):
                if chunk:
                    fd.write(chunk)

    return file_name


def human_readable_size(size, decimal_places=2):
    for unit in ["B", "KB", "MB", "GB", "TB", "PB"]:
        if size < 1024.0 or unit == "PB":
            break
        size /= 1024.0
    return f"{size:.{decimal_places}f} {unit}"


def time_name():
    date = datetime.date.today()
    now = datetime.datetime.now()
    current_time = now.strftime("%H%M%S")
    return f"{date} {current_time}.mp4"


def find_downloaded_file(name):
    """
    Find output file generated by yt-dlp/ffmpeg.
    """
    base = os.path.splitext(name)[0]

    candidates = [
        name,
        f"{name}.mp4",
        f"{name}.mkv",
        f"{name}.webm",
        f"{base}.mp4",
        f"{base}.mkv",
        f"{base}.webm",
        f"{base}.mp4.webm",
    ]

    for file in candidates:
        if os.path.isfile(file):
            return file

    return None


async def download_video(url, cmd, name):
    """
    Linux-safe normal video downloader.
    Works with normal MP4/HLS/non-DRM links through yt-dlp/ffmpeg.
    """
    await asyncio.sleep(2)

    aria2_exists = shutil.which("aria2c") is not None

    extra_args = (
        '-R infinite '
        '--fragment-retries 25 '
        '--socket-timeout 50 '
        f'--user-agent "{USER_AGENT}" '
    )

    if aria2_exists:
        extra_args += (
            '--external-downloader aria2c '
            '--downloader-args "aria2c: -x 16 -j 16 -s 16" '
        )

    download_cmd = f"{cmd} {extra_args}"

    logging.info(download_cmd)
    print(download_cmd)

    max_attempts = 3
    attempt = 0

    while attempt < max_attempts:
        attempt += 1

        proc = await asyncio.create_subprocess_shell(
            download_cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )

        stdout, stderr = await proc.communicate()

        if stdout:
            logging.info(stdout.decode(errors="ignore"))
        if stderr:
            logging.error(stderr.decode(errors="ignore"))

        found = find_downloaded_file(name)

        if proc.returncode == 0 and found:
            return found

        if "visionias" not in cmd.lower():
            break

        await asyncio.sleep(5)

    found = find_downloaded_file(name)
    if found:
        return found

    return None


async def hls_download_ffmpeg(url, name):
    """
    Download non-DRM m3u8/HLS using ffmpeg.
    """
    output = f"{name}.mp4"

    cmd = (
        f'ffmpeg -y '
        f'-headers "User-Agent: {USER_AGENT}\\r\\n" '
        f'-i "{url}" '
        f'-c copy '
        f'-bsf:a aac_adtstoasc '
        f'"{output}"'
    )

    ok = await run(cmd)

    if ok and os.path.exists(output):
        return output

    return None


async def get_drm_keys(url: str):
    """
    DRM key extraction is not supported.
    """
    raise RuntimeError(
        "DRM key extraction/decryption is not supported in this Linux-safe version."
    )


async def drm_download_video(url, qual, name, keys):
    """
    DRM download/decryption is not supported.
    """
    raise RuntimeError(
        "DRM-protected video download/decryption is not supported."
    )


async def send_vid(bot: Client, m: Message, cc, filename, thumb, name, thumb2):
    reply = await m.reply_text(f"**⚡️ Starting Uploading ...** - `{name}`")

    thumbnail = "thumb1.jpg"

    try:
        if thumb != "no" and thumb2:
            cmd = f'wget -q "{thumb2}" -O "{thumbnail}"'
            subprocess.run(cmd, shell=True, check=True)
        else:
            cmd = (
                f'ffmpeg -y -i "{filename}" '
                f'-ss 00:00:12 -vframes 1 "{thumbnail}"'
            )
            subprocess.run(cmd, shell=True, check=True)
    except Exception as e:
        logging.error(f"Thumbnail error: {e}")
        thumbnail = None

    dur = duration(filename)
    start_time = time.time()

    try:
        await m.reply_video(
            filename,
            caption=cc,
            supports_streaming=True,
            height=720,
            width=1280,
            thumb=thumbnail if thumbnail and os.path.exists(thumbnail) else None,
            duration=dur,
            progress=progress_bar,
            progress_args=(reply, start_time),
        )
    except Exception as e:
        logging.error(f"Video upload failed, sending as document: {e}")
        await m.reply_document(
            filename,
            caption=cc,
            thumb=thumbnail if thumbnail and os.path.exists(thumbnail) else None,
            progress=progress_bar,
            progress_args=(reply, start_time),
        )

    try:
        if filename and os.path.exists(filename):
            os.remove(filename)
    except Exception:
        pass

    try:
        if thumbnail and os.path.exists(thumbnail):
            os.remove(thumbnail)
    except Exception:
        pass

    try:
        await reply.delete(True)
    except Exception:
        pass
